apiVersion: apps/v1
kind: Deployment
metadata:
  name: rate-limiter-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rate-limiter-demo
  template:
    metadata:
      labels:
        app: rate-limiter-demo
    spec:
      containers:
        - name: rate-limiter-demo
          image: rate-limiter-demo:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: CMD
              value: "npm run start"